In [1]:
"""
File ufficiale dove implemento la parte di opinion dynamics del mio modello, con matrice delle caratteristiche costante e
matrice di adiacenza variabile.
"""

'\nFile ufficiale dove implemento la parte di opinion dynamics del mio modello, con matrice delle caratteristiche costante e\nmatrice di adiacenza variabile.\n'

PARTE 2) DINAMICA DI RETE CON MATRICE DELLE CARATTERISTICHE COSTANTE

1. IMPORTO LE LIBRERIE NECESSARIE

In [2]:
"""
Importo nel file le librerie e il file con dentro le funzioni ausiliarie che che ho implementato io per poterle usare all' occorrenza.
"""

"\nImporto nel file le librerie e il file con dentro le funzioni ausiliarie che che ho implementato io per poterle usare all' occorrenza.\n"

In [3]:
import networkx as nx
import numpy as np
from funzioni_utili import* #importo tutte le funzioni implementate e salvate nell' altro file
#from funzioni_utili_1 import*
import random as random
import math

PARTE2_a)INIZIO PROVANDO A LANCIARE IL CASO BASE: BASSE T E BASSE N

2. DEFINIZIONE PARAMETRI

In [4]:
"""
Definizione delle costanti o valori iniziali delle variabili che verranno utilizzate nel modello.

"""

'\nDefinizione delle costanti o valori iniziali delle variabili che verranno utilizzate nel modello.\n\n'

In [5]:
N = 2 #numero di nodi
T = 2 #numero di topic
G =nx.Graph()
beta=1
n_time=10 #tempi integraione

3. INIZIALIZZAZIONE MATRICI

In [6]:
"""

Le matrici necessarie per il modello sono:
1) la matrice di adiacenza A
2) la matrice delle caratteristiche C
3) la matrice dei pesi delle caratteristiche W
4) la matrice dei coseni phi

"""


'\n\nLe matrici necessarie per il modello sono:\n1) la matrice di adiacenza A\n2) la matrice delle caratteristiche C\n3) la matrice dei pesi delle caratteristiche W\n4) la matrice dei coseni phi\n\n'

In [7]:
C = np.zeros((n_time,T,N))
W = np.zeros((T,N))
phi = np.zeros((T,T))
A=np.zeros((N,N))

3a)INIZIALIZZAZIONE MATRICE DELLE CARATTERISTICHE

In [8]:
C_0=np.zeros((n_time,T,N))
#print("matrice caratteristiche:\n",C_0)  #prova
#print("tipo:\n",type(C_0))
#C_0=np.ones((T,N))                       #prova
#print("matrice caratteristiche:\n",C_0)

for t in range(n_time):                #prova
    for i in range(T):
        for j in range(N):
            C_0[t][i][j]= random.uniform(-10,10)

print("C_0:\n",C_0)
print("C_0[t]:\n",C_0[t])

C_0:
 [[[-1.201353   -3.33709166]
  [ 7.26689499  3.39647641]]

 [[ 7.5904142   2.20127035]
  [ 1.33607154  4.92134402]]

 [[ 0.43683088 -5.24536577]
  [ 9.41910535 -5.5818112 ]]

 [[ 7.65913217 -9.35473595]
  [ 2.77032734 -3.6863672 ]]

 [[ 7.78417811  4.13958678]
  [-9.80665827 -8.3623263 ]]

 [[-1.47391708  5.21058436]
  [-6.23846936  1.77793362]]

 [[ 8.15871214 -2.19501428]
  [ 5.15923261  8.06250695]]

 [[ 3.64921181  3.33444177]
  [ 7.15964076  6.16132304]]

 [[-8.26816005 -7.24630143]
  [ 5.93536512  9.1220933 ]]

 [[ 8.42937165  9.59895699]
  [-4.62003349 -5.90225946]]]
C_0[t]:
 [[ 8.42937165  9.59895699]
 [-4.62003349 -5.90225946]]


3b)INIZIALIZZAZIONE MATRICE PESI

In [9]:
#ora va inizializzata la matrice dei pesi: la somma degli elementi di ciascuna riga deve fare 1 -> caso base mettiamo tutti i pesi uguale

#esempio:
W = np.array([[0.5,0.5],[0.5,0.5]]) #ok
print("matrice dei pesi:\n",W)
print("tipo:",type(W))
controllo_matrice_pesi(W)      #ok

matrice dei pesi:
 [[0.5 0.5]
 [0.5 0.5]]
tipo: <class 'numpy.ndarray'>
somma 0 : 1.0
somma 1 : 1.0
controllo ok


3c)INIZIALIZZAZIONE MATRICE COSENI

In [10]:
#matrice coseni fissata -> nel caso base è l' identità

phi = np.array([[1,0],[0,1]]) 


print("phi:\n",phi)
print("dimensioni:\n",phi.shape[0])

phi:
 [[1 0]
 [0 1]]
dimensioni:
 2


3d)INIZIALIZZAZIONE MATRICE DI ADIACENZA

In [11]:
#inizializzo una matrice di adiacenza dove tutti i nodi sono collegati

#A_0=np.array([[0,1],[1,0]])  #prova
A_0=np.zeros((N,N))           #prova
A_t=np.zeros((n_time,N,N)) #evoluzione matrice adiacenza
print("matrice di adiacenza:\n",A_0)

matrice di adiacenza:
 [[0. 0.]
 [0. 0.]]


4)CALCOLO MATRICE DI ADIACENZA ADIACENZA A TUTTI I TEMPI

In [12]:
#C_t = np.zeros((n_time,T,N))    #prova

i=0
t=0
for t in range(n_time):
    #C= C_t[t]            #prova
    C= C_0[t]             #prova
    A_t[t] = calcolo_matrice_adiacenza(G,C,beta,phi,W,1)
print("matrice adiacenza:\n",A_t)

#il risultato viene sputato ma i link vengono sempre messi ??? -> c è un problema nella funzione calcolo_matrice_adiacenza (ad alte dimensioni non lo fa)

N= 2
T= 2
vettore x_i:

 vettore x_j:

 vettore w_i:

 vettore w_j:


( 0 0 )
cos_alpha_xy: 1
x= -1.2013529967919805 y= -3.3370916557587886 w_x= 0.5 w_y= 0.5 parziali: 1.0022562653038332
( 0 1 )
cos_alpha_xy: 0
x= -1.2013529967919805 y= 3.396476409671134 w_x= 0.5 w_y= 0.5 parziali: -0.0
( 1 0 )
cos_alpha_xy: 0
x= 7.26689498693219 y= -3.3370916557587886 w_x= 0.5 w_y= 0.5 parziali: -0.0
( 1 1 )
cos_alpha_xy: 1
x= 7.26689498693219 y= 3.396476409671134 w_x= 0.5 w_y= 0.5 parziali: 6.170459348668152
d_numeratore: 7.172715613971985 , tipo: <class 'float'>
numeratore: 0.13941721013615327
( 0 0 )
cos_alpha_xy: 1
x= -1.2013529967919805 y= -3.3370916557587886 w_x= 0.5 w_y= 0.5 parziali: 1.0022562653038332
( 0 1 )
cos_alpha_xy: 0
x= -1.2013529967919805 y= 3.396476409671134 w_x= 0.5 w_y= 0.5 parziali: -0.0
( 1 0 )
cos_alpha_xy: 0
x= 7.26689498693219 y= -3.3370916557587886 w_x= 0.5 w_y= 0.5 parziali: -0.0
( 1 1 )
cos_alpha_xy: 1
x= 7.26689498693219 y= 3.396476409671134 w_x= 0.5 w_y= 0.5 parziali: 6.

In [ ]:
#fino qui ok

PARTE2_b) CASO GENERALE: ALTE T E ALTE N

5) DEFINIZIONE PARAMETRI E COSTANTI

In [13]:
N = 4 #numero di nodi
T = 4 #numero di topic
G =nx.Graph()
beta=5
n_time=10 #tempi integraione

6. INIZIALIZZAZIONE MATRICI

In [14]:
C = np.zeros((n_time,T,N))
W = np.zeros((T,N))
phi = np.zeros((T,T))
A=np.zeros((N,N))

6_a)INIZIALIZZAZIONE MATRICE DELLE CARATTERISTICHE

In [15]:
C_0=np.zeros((n_time,T,N)) #inizializzo matrice delle caratteristiche random a tuttti i tempi    #prova


for t in range(n_time):
    for i in range(T):
        for j in range(N):
            C_0[t][i][j]= random.uniform(-10,10)      #prova

print("C_0:\n",C_0)
print("C_0[t]:\n",C_0[t])

C_0:
 [[[-1.44471565 -4.1090616  -9.37960237 -1.95347041]
  [ 2.49054722 -1.23450465  0.63036199 -1.69089858]
  [-6.60034123 -0.94216007  8.08876617  9.4071263 ]
  [-5.67733598 -8.38067361  2.68542611 -2.02848362]]

 [[-9.36283614 -9.31015297  3.39602972 -3.10718762]
  [-1.60591129 -3.62977148 -7.91809833  3.59279982]
  [ 5.77682647 -7.96980574 -5.46820422 -3.45126738]
  [ 1.09438096 -9.18966883  2.73069417  0.14799779]]

 [[-8.37308537  6.1715537  -8.89866752 -4.72752447]
  [ 4.90351411 -9.49170171 -9.38480813  9.12494607]
  [-0.49563011 -0.03169141  3.01207645  4.53045855]
  [-0.13401169  8.03796928 -5.98133882  2.82423949]]

 [[-8.08842155  9.52041777  8.58082628 -4.11078595]
  [-9.51246053 -4.83630348  5.02794061 -0.21816343]
  [ 8.88181006  8.23829672 -2.32110585 -0.1199998 ]
  [ 8.85645376  3.39097299  4.93650827  0.80780432]]

 [[ 4.69254408  9.83702861 -2.3553239   9.735205  ]
  [ 3.9905823   7.769556   -9.70835628  2.90287708]
  [ 9.67577696 -1.8102575  -4.722699   -1.04885029

6_b) INIZIALIZZAZIONE MATRICE PESI

In [16]:
#esempio:
for i in range(T):
    for j in range(N):
        W[i][j] = random.random()
print("matrice dei pesi:\n",W)
print("tipo:",type(W))
controllo_matrice_pesi(W)      #ok

matrice dei pesi:
 [[0.94355619 0.80077982 0.69387877 0.8453767 ]
 [0.31968668 0.82985705 0.16122772 0.373858  ]
 [0.86066775 0.92477738 0.83521136 0.10403554]
 [0.27772918 0.44682923 0.20572347 0.26707896]]
tipo: <class 'numpy.ndarray'>
somma 0 : 3.2835914818523033
errore



6_c) INIZIALIZZAZIONE MATRICE COSENI

In [17]:
phi = np.identity(T)
print("phi:\n",phi)

phi:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


6_d) INIZIALIZZAZIONE MATRICE ADIACENZA

In [18]:
A_0=np.zeros((N,N))   #prova


for i in range(N):                                          #prova
    for j in range(N):
        if(i == j):
            A_0[i][j] = 0
        else:
            A_0[i][j]=1
#print("A_0=\n",A_0)


A_t=np.zeros((n_time,N,N)) #evoluzione matrice adiacenza

for t in range(n_time):
    A_t[t]=A_0
print("A_t=\n",A_t)

A_t=
 [[[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 [[0. 1. 1. 1.]
  [1. 0. 1. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]]


7. CALCOLO MATRICE ADIACENZA A TUTTI I TEMPI

In [ ]:

print("dimensione  matrice caratteristica tempo t:",np.shape(C_0[4]))
print("elemento C_0[t] al tempo t = ", 4,":\n",C_0[4])
for t in range(n_time):
    C= C_0[t]
    A_t[t] = calcolo_matrice_adiacenza(G,C,beta,phi,W,1)
#print("matrice adiacenza:\n",A_t)

np.save('prova_3',A_t)
del(A_t)                              #salvando A_t e cancellando la shell , le dimensioni del file non aumentano: secondo me a causa di tutti i print che ci sono nella funzione 'calcolo_matrice_adiacenza'

In [ ]:
#domande sull' output:


"""
Errore: fino a N = 4, T=4 funziona, poi da come errore:

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

"""

#NB: dopo qualche iterazione il link viene sempre messo ????
#NB: anche per valori delle caratteristiche negative mi sputa output

#risolto andando su : C:\Users\gianm\.jupyter->jupyter_notebook_config e modificato il valore c.NotebookApp.iopub_data_rate_limit = 10000000