In [1]:
"""
In questo programma provo ad iniziare l' implementazione del modello di opinion dynamics descritto nei files
all' interno della cartella "tesi -> opinion dynamics -> bozza-modello-opinion-dynamics"."""

'\nIn questo programma provo ad iniziare l\' implementazione del modello di opinion dynamics descritto nei files\nall\' interno della cartella "tesi -> opinion dynamics -> bozza-modello-opinion-dynamics".'

PARTE 1) DINAMICA DELLE CARATTERISTICHE A MATRICE DI ADIACENZA COSTANTE

1. IMPORTO LIBRERIE NECESSARIE

In [2]:
"""
Importo nel file le librerie e il file con dentro le funzioni ausiliarie che che ho implementato io per poterle usare all' occorrenza.
"""

"\nImporto nel file le librerie e il file con dentro le funzioni ausiliarie che che ho implementato io per poterle usare all' occorrenza.\n"

In [3]:
import networkx as nx
import numpy as np
from funzioni_utili import* #importo tutte le funzioni implementate e salvate nell' altro file
import random
from eq_differenziale_mio_modello_opinion_dynamics import* #importo tutte le funzioni implementate e salvate nell' altro file


PARTE 1_a)INIZIO PROVANDO A LANCIARE IL CASO BASE

2.DEFINIZIONE PARAMETRI

In [4]:
"""
Definizione delle costanti o valori iniziali delle variabili che verranno utilizzate nel modello.

"""

'\nDefinizione delle costanti o valori iniziali delle variabili che verranno utilizzate nel modello.\n\n'

In [5]:
N = 2 #numero di nodi
T = 2 #numero di topic
K=3
beta=3
alpha=1

h=1 #step integrazione per metodo runge-kutta
n_time=10 #numero iterazioni

3.DEFINIZIONE DELLA RETE 

In [6]:
"""
Introduco una rete Networkx (grafo), calcolando anche la matrice di adiacenza, in formato numpy. Per ora introduco 
solo un grafo vuoto dal momento che la probabilità di avere un link tra due nodi dipenderà dalle 
caratteristiche dei nodi.

"""

'\nIntroduco una rete Networkx (grafo), calcolando anche la matrice di adiacenza, in formato numpy. Per ora introduco \nsolo un grafo vuoto dal momento che la probabilità di avere un link tra due nodi dipenderà dalle \ncaratteristiche dei nodi.\n\n'

In [7]:
"""
#esempio calcolo della matrice di adiacenza in formato numpy
p = 0.6 # per ora così, dopo da definire con funzione, probabilità di avere link tra 2 nodi
G = nx.erdos_renyi_graph(N,p)  #faccio per fare un esempio
A = nx.adjacency_matrix(G).todense() #mi restituisce direttamente la matrice di adiacenza in formato numpy per poterla gestire meglio
print("tipo:",type(A))
print("matrice di adiacenza:\n",A)
"""

'\n#esempio calcolo della matrice di adiacenza in formato numpy\np = 0.6 # per ora così, dopo da definire con funzione, probabilità di avere link tra 2 nodi\nG = nx.erdos_renyi_graph(N,p)  #faccio per fare un esempio\nA = nx.adjacency_matrix(G).todense() #mi restituisce direttamente la matrice di adiacenza in formato numpy per poterla gestire meglio\nprint("tipo:",type(A))\nprint("matrice di adiacenza:\n",A)\n'

In [8]:
#UFFICIALE
G = nx.empty_graph(N) #introduco grafo vuoto con N nodi
print("nodi:",G.nodes())
print("link:",G.edges())

nodi: [0, 1]
link: []


4.INIZIALIZZAZIONE DI TUTTE LE MATRICI NECESSARIE PER IL MODELLO

In [9]:
"""

Le matrici necessarie per il modello sono:
1) la matrice di adiacenza A
2) la matrice delle caratteristiche C
3) la matrice dei pesi delle caratteristiche W
4) la matrice dei coseni phi

"""

'\n\nLe matrici necessarie per il modello sono:\n1) la matrice di adiacenza A\n2) la matrice delle caratteristiche C\n3) la matrice dei pesi delle caratteristiche W\n4) la matrice dei coseni phi\n\n'

In [10]:
C = np.zeros((T,N))
W = np.zeros((T,N))
phi = np.zeros((T,T))
A=np.zeros((N,N))

In [11]:
#occorre ora definire queste matrici utilizzando le funzioni che ho creato, devo ragionare su come fare e come metterle insieme:
#NB: può essere utile ragionare sul foglio creato a mano delle funzioni incluse nella libreria creata da me "funzioni_utili" (fatto)

In [12]:
"""
#ESEMPIO UTILIZZO FUNZIONE IMPORTATA DALLA MIA LIBRERIA

x = [1,1,1]
y = [1,0,1]
N = 3
cos = coseno_angolo_tra_vettori(x,y,N) #la libreria con le mie funzioni è già stata importata (from funzioni_utili import*)
print(cos)

"""

'\n#ESEMPIO UTILIZZO FUNZIONE IMPORTATA DALLA MIA LIBRERIA\n\nx = [1,1,1]\ny = [1,0,1]\nN = 3\ncos = coseno_angolo_tra_vettori(x,y,N) #la libreria con le mie funzioni è già stata importata (from funzioni_utili import*)\nprint(cos)\n\n'


4a) INIZIALIZZO MATRICE DELLE CARATTERISTICHE

In [13]:
#partiamo a inizializzare la matrice delle caratteristiche in maniera random, con valori delle caratteristiche da 0 a 10(le caratteristiche possono assumere qualsiasi valore):

C_0= inizializzazione_matrice_caratteristiche(C) #ok
print("matrice caratteristiche:\n",C_0)
print("tipo:\n",type(C_0))

righe: 2
colonne: 2
i= 0 j= 0
i= 0 j= 1
i= 1 j= 0
i= 1 j= 1
matrice caratteristiche:
 [[9. 8.]
 [8. 3.]]
tipo:
 <class 'numpy.ndarray'>


4b)INIZIALIZZO MATRICE DEI PESI

In [14]:
#ora va inizializzata la matrice dei pesi: la somma degli elementi di ciascuna riga deve fare 1

#esempio:
W = np.array([[0.5,0.5],[0.5,0.5]]) #ok
print("matrice dei pesi:\n",W)
print("tipo:",type(W))
controllo_matrice_pesi(W)      #ok

matrice dei pesi:
 [[0.5 0.5]
 [0.5 0.5]]
tipo: <class 'numpy.ndarray'>
somma 0 : 1.0
somma 1 : 1.0
controllo ok


4c)INIZIALIZZO  MATRICE DEI COSENI

In [15]:
#matrice coseni fissata -> nel caso base è l' identità

phi = np.array([[1,0],[0,1]]) 


print("phi:\n",phi)
print("dimensioni:\n",C.shape[0])

    

phi:
 [[1 0]
 [0 1]]
dimensioni:
 2


4d) INIZIALIZZO LA MATRICE DI ADIACENZA

In [16]:
#inizializzo una matrice di adiacenza dove tutti i nodi sono collegati

A=np.array([[0,1],[1,0]])

print("matrice di adiacenza:\n",A)

matrice di adiacenza:
 [[0 1]
 [1 0]]


5.CALCOLO MATRICE DELLE CARATTERISTICHE A TUTTI I TEMPI

In [39]:
#lancio delle funzioni che mi calcolano la matrice delle caratteristiche a tutti i tempi a matrice di adiacenza fissa


5_a) definisco i vettori di matrici su cui salvare il risultato

In [40]:
 C_t = np.zeros((n_time,T,N))

5_b) richiamo la funzione finale "integrate" che mi sputa il risultato

In [41]:
C_t = integrate(dy,C_0,A,phi,alpha,h,K,W,n_time)
print("matrice delle caratteristiche a tutti i tempi:\n",C_t)

matrice delle caratteristiche a tutti i tempi:
 [[[ 8.00000000e+00  3.00000000e+00]
  [ 5.00000000e+00  6.00000000e+00]]

 [[-3.30326015e+00 -2.57861055e-02]
  [-1.29639731e+00 -1.94455910e+00]]

 [[ 1.09932230e+00 -1.18833019e+00]
  [-5.68131071e-01 -1.00057107e-01]]

 [[-6.22712102e-01  6.13449467e-01]
  [-9.02132863e-02 -2.89725903e-01]]

 [[ 2.71083241e-01 -2.74602287e-01]
  [-1.56682065e-01 -8.14120399e-02]]

 [[-1.03003467e-01  1.00964848e-01]
  [-6.28395765e-02 -9.00345837e-02]]

 [[ 3.55388618e-02 -3.68396526e-02]
  [-5.42269812e-02 -4.45591864e-02]]

 [[-1.31587922e-02  1.23170260e-02]
  [-3.02772835e-02 -3.36919105e-02]]

 [[ 4.20598493e-03 -4.75167993e-03]
  [-2.13297451e-02 -2.01269549e-02]]

 [[-1.75153746e-03  1.39769941e-03]
  [-1.32262815e-02 -1.36494829e-02]]]
