In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from funzioni_utili import*

In [2]:
"""
File dove implemento l' eq 1 pag 3 del paper 10 che descrive l' eq differenziale di come varia nel tempo il
vettore opinione di ciascun nodo i. 

"""

"\nFile dove implemento l' eq 1 pag 3 del paper 10 che descrive l' eq differenziale di come varia nel tempo il\nvettore opinione di ciascun nodo i. \n\n"

1_ Definizione parametri

In [3]:
print("DEFINIZIONE MATRICI E PARAMETRI\n")
print("PARAMETRI:\n")
N=3 #nodi
T=2 #topic
alpha = 0.5 #costante
K = 2 #costante
print("N=",N,"T=",T,"alpha=",alpha,"K=",K)
print("\n")
i = 0 # iteratore
j = 0 # iteratore
t_0 = 0 #tempi di integrazione
t_f = 10
t=0 #per la funzione
n_samples = 100 #numero di punti
t_nsamples = 100
print("t_0=",t_0,"t_f=",t_f,"n_sample =",n_samples,"t_nsamples=",t_nsamples)
print("\n")
t_space = np.linspace(t_0,t_f,t_nsamples)
x_0 = 0 #punto iniziale
print("t_space=",t_space,"x_0=",x_0)
method = 'RK45'  #metodo soluzione usato per approssimare eq differenziale

print("\n")
print("MATRICI:")

A = np.array([[1,1,1],[1,0,0],[1,0,1]]) #matrice di adiacenza(NB:posso sempre trasformare la matrice da adiacenza a numpy con funzione descritta sopra)
#le quadre rappresentano le righe
W=np.array([[0.1,0.5,0.4],[0.3,0.5,0.2]])
C=np.array([[1,0,1],[2,1,1]],dtype = float)  #NB: i valori delle caratteristiche sono float!!!!
print("A=",A)
print("dimensioni A:",np.shape(A)) #matrice adiacenza
print("tipo A:",type(A))
print("\n")
print("W=",W)
print("dimensioni W:",np.shape(W)) #matrice pesi
print("tipo W:",type(W))
print("\n")
print("C=",C)
print("dimensioni C:",np.shape(C)) #matrice caratteristiche
print("tipo C:",type(C))
print("\n")
phi = [[1, 0.2], [0.2, 1]] 

print("phi=",phi)
print("dimensioni phi:",np.shape(phi)) #matrice adiacenza
print("tipo phi:",type(phi))
print("\n")


DEFINIZIONE MATRICI E PARAMETRI

PARAMETRI:

N= 3 T= 2 alpha= 0.5 K= 2


t_0= 0 t_f= 10 n_sample = 100 t_nsamples= 100


t_space= [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.171

2_DEFINIZIONE FUNZIONE PER EQ DIFFERENZIALE : CALCOLO 1 COMPONENTE FISSATA s PER UN VETTORE OPINIONE DI UN NODO i FISSATO AL TEMPO t FISSATO

In [4]:
#i = nodo = fissato
#s = componente nodo = fissato
#t = tempo = fissato (no array) 

In [6]:
#implemento la funzione che mi sputa la variazione della variabile opinione del nodo i sul topic s (x_i)^s a tempo fissato
#(componente s del vettore x_i , a tempo fissato con i e s fissati)

alpha = 0.5 #costante
K = 2 #costante
A = np.array([[1,1,1],[1,0,0],[1,0,1]]) #matrice di adiacenza(NB:posso sempre trasformare la matrice da adiacenza a numpy con funzione descritta sopra)
#le quadre rappresentano le righe ->costante
W=np.array([[0.1,0.5,0.4],[0.3,0.5,0.2]]) #-> costante
C=np.array([[1,0,1],[2,1,1]],dtype = float) # -> costante
phi = [[1, 0.2], [0.2, 1]]  #-> costante
i = 1 # fissato
s = 1 #fissato
t=0 # il tempo c è nella funzione ma non varia -> fissato
print("*///////////////////////////////////////////////////////*")

#IMPLEMENTAZIONE FUNZIONE



#/////////////////////////////////////////////////////////////////////////////////////////////////////////

def dinamica_variabile_opinione(A, alpha, K, C,W,phi,i,s):
    
    # i = nodo che sto considerando(riga della matrice A da prendere e colonna della matrice caratteristica C) -> variabile ma fissato
    #j = tutti gli altri nodi escluso quello considerato
    #s = componente del vettore opinione che sto considerando (componenti del vettori phi*x*w da prendere) -> riga della matrice caratteristica -> variabile ma fissato
    #x_j = vettore iniziale della matrice delle caratteristiche di cui faccio la dinamica(colonna i della matrice C)
    #t = la funzione dipenderà dal tempo. Serve per eq differenziale e variando il tempo varieranno anche altri input come A,C,W,phi -> qui è a tempo costante
    # A = matrice di adiacenza ->per ora costante
    # alpha, K = costanti (numeri)
    # C = matrice delle caratteristiche -> costante
    #W = matrice dei pesi -> costante
    #phi = matrice coseni -> costante
    
    
    #0) definisco le variabili
    
    j=0
    elem = 0   #elementi della sommatoria
    prod1 = 0
    prod2 = 0
    w_j = [] #ci salviamo la colonna w_j della matrice dei pesi W
    x_j = [] # ci salviamo la colonna j della matrice delle caratteristiche C
    valore_finale_variazione_componente = 0 #valore finale della componente s del vettore caratteristica del nodo i
    
    #1) definisco le dimensioni delle matrici
    
    N = int(A.shape[1])
    T = int(C.shape[0])
    while( j < N ):  #mi indica la sommatoria
        
        if(j != i):
            
            #2)estraggo le colonne dalle matrici W e C 
            
            w_j = estrai_colonna_matrice(W,N,T,j)
            x_j = estrai_colonna_matrice(C,N,T,j)
            
            #3)implemento la sommatoria su j
            
            prod1 = np.multiply(w_j,x_j) #fa il prodotto componente per componente e restituisce un vettore
            prod2  = np.dot(phi,prod1) #questo dovrebbe essere un vettore
            elem = elem + A[i][j]*np.tanh(alpha*prod2[s]) #singolo elemento della sommatoria(NB: devo prendere la componente s di prod2)
            j = j+1 #scorro su un altro nodo (sempre diverso da i)
            
        else:
            elem = elem + 0
            j=j+1
    # ho ottenuto ora il valore della sommatoria su j
            
            
    
    #4) Moltiplico per K 
    valore_finale_variazione_componente = K * elem
    #print("valore variazione componente",s,"del vettore",i,":",valore_finale_variazione_componente )
    
    #5) sommo il valore dell' elemento trovato alla componente s del vettore caratteristica del nodo i (differenza), ovvero l' elemento 
    # [s][i]  della matrice delle caratteristiche:
    
    
    valore_finale_variazione_componente = valore_finale_variazione_componente - C[s][i] # ho così ottenuto il valore della parte destra dell' equazione 1 per la componente s(fissata) del vettore opinione del nodo i(fissato)
    
   
    
    return  valore_finale_variazione_componente
    


#////////////////////////////////////////////////////////////////////////////////////////////////////
# LANCIO DI PROVA

print("\n")
print("LANCIO DI PROVA DELLA FUNZIONE:\n")       
delta_x_s = 0
i = 1
s = 1
delta_x_s = float(dinamica_variabile_opinione(A, alpha, K, C,W,phi,i,s))
print("tipo output:",type(delta_x_s))
print("[valore finale elemento elemento di C (s, i ) :=","(",s,",",i,")]","=",delta_x_s)
print("\n")

print("*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*")
print("\n")
print("MODIFICA MATRICE DELLE CARATTERISTICHE")


C = modifica_matrice_caratteristiche(C,s,i,delta_x_s)
print("matrice delle caratteristiche modificata:\n",C)

*///////////////////////////////////////////////////////*


LANCIO DI PROVA DELLA FUNZIONE:

tipo output: <class 'float'>
[valore finale elemento elemento di C (s, i ) := ( 1 , 1 )] = -0.3991258057046917


*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*


MODIFICA MATRICE DELLE CARATTERISTICHE
matrice delle caratteristiche modificata:
 [[ 1.          0.          1.        ]
 [ 2.         -0.39912581  1.        ]]


3_IMPLEMENTAZIONE CHIAMATA EQ DIFFERENZIALE

3a_PROVO A RICAVARE UNA SOLA COMPONENTE DI UN SINGOLO VETTORE A TUTTI I TEMPI

In [6]:
#questa da non guardare!!!!!!!!!!!!

In [7]:
#s = componente del vettore = fissata
#t = array di valori = variabile
#i = nodo = vettore opinione = fissato

In [8]:
#parametri da passare alla funzione:
#alpha = 0.5 #costante
#K = 2 #costante
#A = np.array([[1,1,1],[1,0,0],[1,0,1]]) #matrice adiacenza ->costante
#W=np.array([[0.1,0.5,0.4],[0.3,0.5,0.2]]) #costante
#C=np.array([[1,0,1],[2,1,1]],dtype = float)  #NB: i valori delle caratteristiche sono float!!!! ->costante
#phi = [[1, 0.2], [0.2, 1]] #->costante
#i = 1 #-> costante, nodo che sto considerando
#s=1 #-> costante, componente del vettore opinione del nodo i che sta variando
#t_0 = 0 #tempi di integrazione
#t_f = 10
#t_nsamples = 100
#t_space = np.linspace(t_0,t_f,t_nsamples) #tempo è variabile
#x_0 = 0 #punto iniziale -> costante
#method = 'RK45'  #metodo soluzione usato per approssimare eq differenziale
#variabile in output: valore_finale_variazione_componente (componente s del vettore opinione del nodo i, la funzione dovrebbe sputare il suo valore a ciascun tempo dell' array t_space)

In [9]:
#Chiamata della funzione: lambda vuole 2 input e la devo usare perchè se no non prende la funzione.Ora chiaramente le variabili sono t e il 
#vettore opinione x. Io qui avevo messo x , che però non è direttamente presente all' interno della funzione. Cosa ci devo mettere al suo posto?


#ho pensato di metterci x_j che è l' analogo del vettore x presente nella funzione,va bene?? DA FAR VEDERE??????
#ode_fn = lambda t,x_j: dinamica_variabile_opinione(A, alpha, K, C,W,phi,i,s,t) #va bene con lambda mettere t e x_j???

In [10]:
#num_sol = solve_ivp(ode_fn,[t_0,t_f],[x_0],method = method, dense_output = True) #chiaramente da sempre lo stesso valore perchè qui A e C non variano nel tempo, ma nel file finale varieranno
#print(num_sol)
#T = num_sol.t
#print("tempi a cui integro:\n",T)
#Y = num_sol.y
#print("array i cui elementi sono il valore della componente s del vettore opinione del nodo i per tutti i tempi dell' array t_space:\n")
#print(Y)
#print("dimensioni di Y:",np.shape(Y))


3b)CHIAMATA DELLA FUNZIONE 1: OCCORRE ORA CALCOLARE TUTTE LE COMPONENTI DEI VETTORI OPINIONE DI TUTTI I NODI, A TEMPO FISSATO (MATRICE DELLE CARATTERISTICHE C A TEMPO FISSATO)

In [11]:
#s =  variabile = tutte le componenti del vettore da 1 a T
#t = fissato , non incide nella funzione
#i = nodo = vettore opinione = variabile da 1 a N (nodi)

In [12]:
#parametri da passare alla funzione:
alpha = 0.5 #costante
K = 2 #costante
A = np.array([[1,1,1],[1,0,0],[1,0,1]]) #matrice adiacenza ->costante
W=np.array([[0.1,0.5,0.4],[0.3,0.5,0.2]]) #costante
C=np.array([[1,0,1],[2,1,1]],dtype = float)  #NB: i valori delle caratteristiche sono float!!!! ->costante
N = int(C.shape[1]) #nodi
T = int(C.shape[0]) #topic
phi = [[1, 0.2], [0.2, 1]] #->costante
i = 1 #-> variabile, nodo che sto considerando
s=1 #-> variabile, componente del vettore opinione del nodo i che sta variando
t_0 = 0 #tempi di integrazione
t_f = 10
t_nsamples = 100
t_space = np.linspace(t_0,t_f,t_nsamples) #tempo è variabile, ma qui non incide nella funzione(costante)
x_0 = 0 #punto iniziale -> costante
method = 'RK45'  #metodo soluzione usato per approssimare eq differenziale


In [13]:
#funzione che calcola la matrice delle caratteristiche  di tutti i nodi (matrice di tutti i vettori (x_i)^s al variare di s)
# a tempo fissato per tutte le caratteristiche.

def vettore_opinione_evoluto(A, alpha, K, C,W,phi):
    
    #1)DEFINIZIONE VARIABILI
    # t è costante
    #C in input è costante
    #i e s variano
    s=0 
    i=0
    N = int(C.shape[1])
    T = int(C.shape[0])
    D = np.zeros((T,N)) # matrice 
    
    #2)CICLO INCUI RICHIAMO LA FUNZIONE DINAMICA_VARIABILE_OPINIONE PER CALCOLARE I SINGOLI ELEMENTI DI MATRICE
    for s in range(T):
        for i in range(N):
            delta_i_s =  dinamica_variabile_opinione(A, alpha, K, C,W,phi,i,s)
            D[s][i] =  delta_i_s 
            
        
    return D

D = np.zeros((T,N))
D = vettore_opinione_evoluto(A, alpha, K, C,W,phi)
print("matrice delle caratteristiche a t = 0 fissato:\n",D)

matrice delle caratteristiche a t = 0 fissato:
 [[-0.46704713  0.21911694 -0.78088306]
 [-1.23197778 -0.39912581 -0.39912581]]


In [14]:
#FINO QUI OK!

3c) CHIAMATA DELLA FUNZIONE 2:FUNZIONE CHE MI CALCOLA LA MATRICE DELLE CARATTERISTICHE PER TUTTI I NODI A TUTTI I TEMPI

In [15]:
#serie di funzioni che calcola la matrice delle caratteristiche  di tutti i nodi (matrice di tutti i vettori (x_i)^s al variare di s)
# a tutti i tempi per tutte le caratteristiche. L' output sarà un vettore di matrici (TxN) di t componenti.

In [16]:
#s = array di valori = variabile = tutte le componenti del vettore da 0 a T
#t = array di valori = variabile
#i = nodo = vettore opinione = variabile da 1 a N (nodi)

In [17]:
#parametri da passare alla funzione:
alpha = 0.5 #costante
K = 2 #costante
A = np.array([[0,1,0],[1,0,1],[0,1,0]]) #matrice adiacenza ->costante  #NB: [0,1,0]... sono le righe
W=np.array([[0.1,0.5,0.4],[0.3,0.5,0.2]]) #costante
C=np.array([[1,0,1],[2,1,1]],dtype = float)  #NB: i valori delle caratteristiche sono float!!!! ->costante
N = int(C.shape[1]) #nodi
T = int(C.shape[0]) #topic
phi = [[1, 0.2], [0.2, 1]] #->costante
i = 1 #-> variabile, nodo che sto considerando
s=1 #-> variabile, componente del vettore opinione del nodo i che sta variando
t_0 = 0 #tempi di integrazione
t_f = 10
t_nsamples = 10
t_space = np.linspace(t_0,t_f,t_nsamples) #tempo è variabile
max_step = (t_f - t_0)/t_nsamples
x_0 = 0 #punto iniziale -> costante
method = 'RK45'  #metodo soluzione usato per approssimare eq differenziale


D_0 = np.ones((T,N)) #condizioni iniziali (matrice delle caratteristiche iniziali)
t=0 #variabile tempo: sarà solo formale negli input delle funzioni , ma varierà implicitamente variando la matrice delle caratteristiche C ad ogni step
h = 1 #step per il metodo runge_kutta


In [18]:
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

In [19]:
"""
#prova chiamata metodo runge_kutta per singolo step temporale: quella sotto è quella implementata da me per normali funzioni, da modificare per il mio caso


def Runge_Kutta_4_order(dy,h,x_0,y_0,output,n,f):
    #dy = eq differenziale
    #h = incremento
    #x_0,y_0 = valori iniziali delle variabili
    #output = se vale 1 la funzione restituisce x_plot,se vale 2 la funzione restituisce y_RK_4(lista di valori che approssimano la soluzione dell' eq differenziale con Runge Kutta), se vale 3 la funzione restituisce y_analytical (lista di valori di y calcolati con la funzione che risolve analiticamente l' eq differenziale sui valori di x scelti.(serve solo per verifica,si può omettere se non si conosce la soluzione))
    #x_plot = lista di valori della variabile x su cui approssimo la soluzione dell eq differenziale con Runge Kutta(scelta da me)
    # n = numero di iterazioni metodo Runge Kutta
    #f = funzione che risolve analiticamente l' eq differenziale (serve solo come verifica della funzione soluzione dell' eq differenziale ottenuta con Runge Kutta, y_RK_4)
    x_plot = []
    y_RK4 = [] # lista di valori di y corrispondenti ai valori di x scelti, calcolati con la funzione ricavata con metodo Runge Kutta (approssimati, NB:non è una funzione ma una lista di valori)
    y_analytical = [] #lista di valori di y corrispondenti ai valori di y scelti, calcolati con la funzione che risolve analiticamente l' eq differenziale(serve solo per confronto, di norma non la conosco.Non serve per metodo ma per verifica) NB:calcolati applicando la funzione ai valori di x
    
    x = x_0
    y = y_0 #valori iniziali
    #RK4 Method
    for i in range(1,n+1):
        x_plot.append(x)
        y_RK4.append(y)
        #y_analytical.append(f(x))
        #calculate derivate approximation
        k_1 = dy(x,y)
        k_2 = dy(x + h/2 , y + k_1 * h/2)
        k_3 = dy(x + h/2 , y + k_2 * h/2)
        k_4 = dy(x + h , y + k_3 * h)
        #calculate new y estimation
        y = y + 1/6 * ( k_1 + 2 * k_2 + 2 * k_3 + k_4) * h
        #increase x by stepsize to calculate new y estimate
        x = x + h
        #print('x=%f \t y=%f \t f(x)=%f'%(x,y,f(x)) )
    if(output == 1):
        print("x_plot:")
        return x_plot
    if(output == 2):
        print("y_RK4:")
        return y_RK4
    if(output == 3):
        print("y_analytical:")
        return y_analytical

"""

#prima di provare a riscrivere la funzione per il metodo Runge-Kutta occorre definire delle funzioni preliminari:
#1)dy = richiama la funzione vettore_opinione_evoluto, ma per singolo step temporale.Il tempo (non esplicito) varierà cambiando C
#  è una funzione che serve per richiamare vettore_opinione_evoluto a tempo singolo, potendo variare gli input t e C
#2) RK4_step = calcola la matrice delle caratteristiche con il metodo Runge Kutta dopo 1 singolo step temporale
#3) integrate = richiama la funzioneRK4_step a tutti i tempi, variando la matrice C in input a ogni step(e quindi implicitamente il tempo)


#NB: alla fine se andranno bene puoi toglierle da qui e metterle nel file funzioni_utili.py

'\n#prova chiamata metodo runge_kutta per singolo step temporale: quella sotto è quella implementata da me per normali funzioni, da modificare per il mio caso\n\n\ndef Runge_Kutta_4_order(dy,h,x_0,y_0,output,n,f):\n    #dy = eq differenziale\n    #h = incremento\n    #x_0,y_0 = valori iniziali delle variabili\n    #output = se vale 1 la funzione restituisce x_plot,se vale 2 la funzione restituisce y_RK_4(lista di valori che approssimano la soluzione dell\' eq differenziale con Runge Kutta), se vale 3 la funzione restituisce y_analytical (lista di valori di y calcolati con la funzione che risolve analiticamente l\' eq differenziale sui valori di x scelti.(serve solo per verifica,si può omettere se non si conosce la soluzione))\n    #x_plot = lista di valori della variabile x su cui approssimo la soluzione dell eq differenziale con Runge Kutta(scelta da me)\n    # n = numero di iterazioni metodo Runge Kutta\n    #f = funzione che risolve analiticamente l\' eq differenziale (serve solo co

3c_a) FUNZIONE dy

In [20]:

def dy(A,alpha,K,C,W,phi,t):
    
    #a)dimensioni
    N = int(C.shape[1])
    T = int(C.shape[0])
    
    #b) introduco matrice di zeri per output finale
    dC = np.zeros((T,N))
    
    #c) richiamo la funzione vettore_opinione_evoluto per riempire la matrice
    dC=vettore_opinione_evoluto(A,alpha,K,C,W,phi)
    
    return dC

#prova

dC = dy(A,alpha,K,C,W,phi,t)
print("matrice caratteristiche:\n",dC)

matrice caratteristiche:
 [[-0.90008325  0.65215306 -0.90008325]
 [-1.51016268 -0.12094091 -0.51016268]]


3c_b) FUNZIONE RK4_STEP

In [21]:

#NB: C_0 è la matrice delle caratteristiche iniziale, al primo step coinciderà con D_0, ai successivi ovviamente no.
def RK4_step(dy,C_0,A,phi,alpha,h,K,W):
    
    #a)dimensioni
    N = int(C.shape[1])
    T = int(C.shape[0])
    
    #a1) inizializzo matrici e variabili
    
    t=0 #definisco t poichè qui dovrà variare
    C_new = np.zeros((T,N))
    
    
    #b)definisco i vari passi del metodo Runge Kutta
    
    k_1 = dy(A,alpha,K,C_0,W,phi,t)
    k_2 = dy(A,alpha,K,C_0 + (h/2)*k_1,W,phi,t+h/2)
    k_3 = dy(A,alpha,K,C_0 + (h/2)*k_2,W,phi,t+h/2)
    k_4 = dy(A,alpha,K,C_0 + h*k_3,W,phi,t+h)
    
    #c) calcolo la nuova matrice delle caratteristeiche al tempo t+1
    C_new = h/6 *(k_1 + 2*k_2 + 2*k_3 + k_4)
    
    return C_new


C_new = np.zeros((T,N))
C_new = RK4_step(dy,D_0,A,phi,alpha,h,K,W)
print("C_new:\n",C_new)

C_new:
 [[-0.33610482 -0.33437109 -0.33610482]
 [-0.33586008 -0.33349688 -0.33586008]]


3c_c) FUNZIONE INTEGRATE

In [22]:

def integrate(dy,C_0,A,phi,alpha,h,K,W,n_time):
    
    #a) dimensioni
    N = int(C_0.shape[1])
    T =int(C_0.shape[0])
    
    #b)introduco allocazione di memoria per output: vettore di n_time componenti composto da matrici TxN
    C_t = np.zeros((n_time,T,N))
    C_t[0]=C_0  #inizializzo
    
    #c)ciclo che richiama il metodo Runge Kutta a 1 singolo step temporale, per n_time volte, aggiornando ad ogni step la matrice C in input
    
    i=0
    
    for i in range(1,n_time):
        
        C_new = RK4_step(dy,C_0,A,phi,alpha,h,K,W) #richiama Runge Kutta al singolo step temporale
        C_t[i] = C_new #salva il risultato come componente del vettore in output
        C_0 = C_new #aggiorna la matrice delle caratteristiche in input ad ogni iterazione temporale con quella ottenuta nello step precedente
        
    return C_t

n_time=10
C_t = np.zeros((n_time,T,N))
D_0 = np.ones((T,N)) #condizioni iniziali (matrice delle caratteristiche iniziali)

C_t = integrate(dy,D_0,A,phi,alpha,h,K,W,t_nsamples)
print("matrice caratteristiche tutti tempi:\n",C_t)
print("elemento di matrice C_t[1]:\n",C_t[1])
print("elemento di matrice C_t[1][0]:\n",C_t[1][0])
print("elemento di matrice C_t[1][0][1]:\n",C_t[1][0][1])

#NB: ok ma i valori :
# C[t][i][j] = C[t][i][j+1] (provato a cambiare matrici iniziali e vengono diversi)

matrice caratteristiche tutti tempi:
 [[[ 1.00000000e+00  1.00000000e+00  1.00000000e+00]
  [ 1.00000000e+00  1.00000000e+00  1.00000000e+00]]

 [[-3.36104822e-01 -3.34371085e-01 -3.36104822e-01]
  [-3.35860078e-01 -3.33496879e-01 -3.35860078e-01]]

 [[ 1.11413893e-01  1.10078567e-01  1.11413893e-01]
  [ 1.11376678e-01  1.09565929e-01  1.11376678e-01]]

 [[-3.70162441e-02 -3.60366518e-02 -3.70162441e-02]
  [-3.70624458e-02 -3.57409926e-02 -3.70624458e-02]]

 [[ 1.24053962e-02  1.16884908e-02  1.24053962e-02]
  [ 1.24717797e-02  1.15096387e-02  1.24717797e-02]]

 [[-4.23636947e-03 -3.71179988e-03 -4.23636947e-03]
  [-4.29897928e-03 -3.59850930e-03 -4.29897928e-03]]

 [[ 1.50329716e-03  1.11948635e-03  1.50329716e-03]
  [ 1.55496249e-03  1.04498416e-03  1.55496249e-03]]

 [[-5.73328750e-04 -2.92522346e-04 -5.73328750e-04]
  [-6.13431482e-04 -2.42129323e-04 -6.13431482e-04]]

 [[ 2.45720747e-04  4.02863374e-05  2.45720747e-04]
  [ 2.75857139e-04  5.51314076e-06  2.75857139e-04]]

 [[-1.22